stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  # Add image registry info
  IMAGE_TAG: $CI_REGISTRY_IMAGE/ml-service:$CI_COMMIT_REF_SLUG

services:
  - docker:dind

build-ml-service:
  image: docker:latest
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG ./ml-service -f ml_service/Dockerfile .
    - docker push $IMAGE_TAG


test-ml-service:
  image: docker:latest
  stage: test
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG
    - docker run -d --name ml-test $IMAGE_TAG
    - sleep 10  # give it time to start
    - |
      # Use the container IP address instead of localhost
      CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ml-test)
      # Install curl in the Docker image
      apk add --no-cache curl
      # Test the service
      curl --fail http://localhost:8000/health || (echo "API test failed" && exit 1)
    - docker stop ml-test