stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apt-get update && apt-get install -y docker.io curl
  - docker info

build-ml-service:
  stage: build
  script:
    - docker build -t ml-service ./ml-service

test-ml-service:
  stage: test
  script:
    - docker run -d -p 8000:8000 --name ml-test ml-service
    - sleep 10  # give it time to start
    - |
      # Example test - update with real API endpoints
      curl --fail http://localhost:8000/health || (echo "API test failed" && exit 1)
    - docker stop ml-test
