stages:
  - build
  - test

# Build the Docker image
build_ml:
  stage: build
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  script:
    # Build the image
    - docker build -t my_ml_service -f ml_service/Dockerfile .
  tags:
    - docker

# Run tests using the built image
test_ml:
  stage: test
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"  # Ensures Docker connects to the right daemon
  script:
    # Run tests using the locally built image
    - docker run --rm my_ml_service pytest > result.log; tail -n 10 result.log
  tags:
    - docker

