stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  # Add this to use the Docker host from DinD
  DOCKER_HOST: tcp://docker:2375
  # Use TLS=false for simplicity in CI environment
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

build-ml-service:
  image: docker:latest
  stage: build
  script:
    - docker build -t ml-service -f ml_Service/Dockerfile .


test-ml-service:
  image: docker:latest
  stage: test
  script:
    - docker run -d --name ml-test ml-service
    - sleep 10  # give it time to start
    - |
      # Use the container IP address instead of localhost
      CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ml-test)
      # Install curl in the Docker image
      apk add --no-cache curl
      # Test the service
      curl --fail http://$CONTAINER_IP:8000/health || (echo "API test failed" && exit 1)
    - docker stop ml-test