stages:
  - build
  - test

# Build the Docker image
build_ml:
  stage: build
  image: docker:20.10.7 
  # services:
  #   - docker:20.10.7-dind
  # variables:
  #   DOCKER_HOST: tcp://docker:2375
  script:
    - docker build -t my_ml_service -f ml_service/Dockerfile .
  tags:
    - docker

# Run tests using pytest
test_ml:
  stage: test
  image: python:3.12-slim
  script:
    - pip install pytest httpx 
    - pytest > result.log; tail -n 10 result.log
