stages:
  - build
  - test

# Build the Docker image
build_ml:
  stage: build
  image: docker:20.10.7 
  script:
    - docker build -t ml_service/my_ml_service .

# Run tests using pytest
test_ml:
  stage: test
  image: python:3.12-slim
  script:
    - pip install pytest httpx 
    - pytest > result.log; tail -n 10 result.log
